all:merge_sort.cpp
	@echo""
	@echo =========== COMPILING ============ 
	@g++ -pthread -g merge_sort.cpp -o merge
	@./loading.sh
	@echo ========   PROGRAMM RUNING   ========== 
	@./merge


clean:
	rm merge
