all:insert_sort.cpp
	@echo""
	@echo =========== COMPILING ============ 
	@g++ -pthread -g insert_sort.cpp -o insert
	@./loading.sh
	@echo ========   PROGRAMM RUNING   ========== 
	@./insert


clean:
	rm insert
