all:select_sort.cpp
	@echo""
	@echo =========== COMPILING ============ 
	@g++ -pthread -g select_sort.cpp -o select
	@./loading.sh
	@echo ========   PROGRAMM RUNING   ========== 
	@./select


clean:
	rm select
