all:bubble_sort.cpp
	@echo""
	@echo =========== COMPILING ============ 
	@g++ -pthread -g bubble_sort.cpp -o bubble
	@./loading.sh
	@echo ========   PROGRAMM RUNING   ========== 
	@./bubble


clean:
	rm bubble
